### PR TITLE
Add forge testing

### PR DESCRIPTION
**Pull request by shunkakinoki**
Added bare minimal `forge testing`

### CODE REVIEW

**Comment by shunkakinoki** [comment]
i don't know why it isn't working (working locally)

**Comment by shunkakinoki** [comment]
@Jon-Becker 
Okay it's working! 
It was a file name mistake

https://github.com/shunkakinoki/renoun/runs/6696627705?check_suite_focus=true

**Comment by Jon-Becker** [comment]
@rootulp Fixed the renderer!

**Comment by shunkakinoki** [comment]
Awesome! should i add a test or too for the renderer too?

**Comment by Jon-Becker** [comment]
I'll implement more tests soon

**Comment by shunkakinoki** [comment]
Awesome! thank you💪

**Comment by shunkakinoki** [comment]
closing this for now..!

**Pull request closed without merging**
