### PR TITLE
attempt 2 😅

### PR DESCRIPTION
**Pull request by shunkakinoki**
Address: 0x4fd9d0ee6d6564e80a9ee00c0163fc952d0a45ed

### CODE REVIEW

**Comment by shunkakinoki** [comment]
shoot! thank you!!

**Comment by Jon-Becker** [comment]
If the image doesnt render, Itll be fixed when I redo the renderer (#11)

**Comment by shunkakinoki** [comment]
THANK YOU ser!!

**Comment by shunkakinoki** [comment]
Thank you ser!

**Pull request merged**
